### ISSUE TITLE
syntax highlight randomly crashed when editing/scrolling through vue SFC

### ISSUE THREAD

**Issue by lzl19971215** [yaegassy/coc-volar#307]
Hi, 
I have installed coc-volar and enable take over mode in my vue project. I find volar syntax highlight crashed randomly when I edit or browse through a SFC vue file:
![image](https://github.com/yaegassy/coc-volar/assets/63151530/cdcfeac7-9f41-41b0-a657-3024e7c5cf75)

this is my coc log:
![image](https://github.com/yaegassy/coc-volar/assets/63151530/447dc174-2b92-4a38-a071-1d411798ae9f)

Can anyone help? Thanks!

**Comment by yaegassy** [comment]
I think `notifiacation: highlight []` you are seeing in your logs is due to the inclusion of this setting shown in the README for coc.nvim. However, I don't think this is a particular problem, but if you are concerned about that log, try removing it from the configuration file.

- <https://github.com/neoclide/coc.nvim/blob/master/README.md?plain=1#L162-L163>

I think the frequent crashe of syntax highlighting in Vue files is other problem. Try adding a syntax highlighting plugin for Vue or use nvim-treesitter

- [leafOfTree/vim-vue-plugin](https://github.com/leafOfTree/vim-vue-plugin)
- [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter)

**Comment by lzl19971215** [comment]
Thanks a lot, adding a syntax highlighting plugin for Vue can solve this problem!
