### ISSUE TITLE
Duplicate completion suggestions in `.ts` files

### ISSUE THREAD

**Issue by hexh250786313** [yaegassy/coc-volar#345]
![image](https://github.com/yaegassy/coc-volar/assets/26080416/af676419-1174-41b8-b00e-46d78b3c9f59)

Both of two files are in the same vue project, but as you can see from the screenshot, the `.vue` file has normal suggestions, but the `.ts` file has duplicate suggestions.

Moreover, in the `.ts` file of non-vue projects, there are also duplicate suggestions, also caused by coc-volar, even if I set `"volar.enable"` to `false`, it can't be avoided, and the only way to get back to normal is to uninstall coc-volar completely.

I can reproduce it in https://github.com/jekip/naive-ui-admin with an empty `coc-settings.json`.

If you need any additional information, I'll provide it in the reply below.

**Comment by yaegassy** [comment]
Hi. Thank you for reporting the issue. I am experiencing the same symptoms in my environment. I will investigate to see if I can make adjustments to avoid affecting the tsserver.

It is likely that this issue is related to the tsplugin.

- <https://github.com/yaegassy/coc-volar/blob/8f0d27b83baf3cf6720ca57865ce3bbada677f6e/package.json#L322-L333>

**Comment by yaegassy** [comment]
@hexh250786313 The adjustments are complete, and the new version has been published to npm.

**Comment by hexh250786313** [comment]
@yaegassy It's working fine now. I tested it in both vue and non-vue projects. Awesome thanks for such a quick fix!
